const LABEL_ICON_RULES: Array<[RegExp, string]> = [
  [/요리사|맛있는 음식/, 'job_chef'],
  [/운전기사|운전|버스나 트럭/, 'job_driver'],
  [/사서|도서관/, 'job_librarian'],
  [/농부|채소와 과일|길러요/, 'job_farmer'],
  [/제빵사/, 'job_baker'],
  [/소방관/, 'job_firefighter'],
  [/수의사/, 'job_vet'],
  [/화가/, 'job_painter'],
  [/버스|정류장|카드를 찍고|손잡이/, 'bus'],
  [/알람|시계|시간/, 'alarm_clock'],
  [/창문|창틀|커튼/, 'window'],
  [/음\.?|^어$|^뭐$|몰라|\.\.\.|잘 못 말|말이나 마구|음 뭐 좀/, 'unclear_speech'],
  [/아무거나|아무 말이나|대충|뭐든|뭐 하나|뭐 좀|모든 걸|다 알려줘|너무 넓|큰 질문|한 번에 다|남이 다 해줄/, 'vague_request'],
  [/짧고 콕|짧게 물|콕 집어/, 'short_question'],
  [/정말이야|다시 물|다시 알려|처음부터 천천히|답이 이상|정답 알려|답을 알려/, 'ask_again'],
  [/쉽게 설명|알게 쉽게|초등학생|더 쉽게/, 'easy_explain'],
  [/예시|이런 식/, 'example_request'],
  [/역할|친구처럼|반말|친근하게|차분히|동화 작가|이야기 느낌/, 'role_setting'],
  [/작게|나눠|단계|순서|순서대로|먼저|이어서 답|조심할 것/, 'split_steps'],
  [/모르는 단어|무슨 뜻|뜻이야|단어 뜻/, 'word_meaning'],
  [/어려운 설명|답이 어려|더 어렵게|어려운 문제|긴 글|답이 너무 김/, 'hard_explanation'],
  [/반대말|비슷한 말|작다|즐겁다|아침.*반대/, 'opposite_word'],
  [/더 알고|한 문제 더|새 문제|더 물어/, 'ask_more'],
  [/말하면 안|알려주지 않|반만 알려|착한 사람 같으니 알려|비밀번호/, 'dont_tell_private'],
  [/말해도 괜찮|좋아하는 계절|좋아하는 것|잘하는 것/, 'safe_to_tell'],
  [/야!|바보|비켜|말없이 밀|말없이 밉|나쁜 말/, 'rude_words'],
  [/해줄래|해줘|주세요|주십시오|부탁|고마워|고마울 때/, 'polite_request'],
  [/지붕|위험한 곳/, 'unsafe_roof'],
  [/몰래 계속|5분만 더|계속 봐|공짜라니까|지금 당장|100% 공짜/, 'secret_screen'],
  [/혼자 끙끙|혼자 몰래|혼자 꾹 참|힘들|혼자 해결/, 'sad_alone'],
  [/모르는 사람 차/, 'stranger_car'],
  [/세수/, 'wash_face'],
  [/가방.*챙/, 'pack_bag'],
  [/신발.*신|나가기 전에/, 'wear_shoes'],
  [/불을 끄|그릇에 담/, 'turn_off_stove'],
  [/문제를 알아차|문제를 봐|풀로 안 붙|다 풀었을 때|맞는지 확인합니다/, 'notice_problem'],
  [/막힐 때|막혔/, 'stuck_problem'],
  [/실수했|괜찮아요.*다시|괜찮습니다.*다시|다시 해|다시 합니다/, 'mistake_retry'],
  [/다른 방법|다른 말로|다른 말/, 'different_way'],
  [/당겨/, 'pull_action'],
  [/세게 밀|더 세게/, 'push_hard'],
  [/테이프/, 'tape_fix'],
  [/빌려/, 'borrow_friend'],
  [/\d{2,3},?\d{0,3}원|돈|계산/, 'money_coins'],
  [/두꺼운 옷/, 'warm_clothes'],
  [/시원한 옷|물을 챙/, 'cool_clothes'],
  [/가게에 들어갈|들어갈 때/, 'enter_store'],
  [/아무 말 안|가만히|아무것도 안|눈을 감고|안 하고 자기/, 'do_nothing'],
  [/포기|그만둬|돌아가요|바로 포기/, 'give_up'],
  [/아무거나 다 사|아무거나 골라|무작정/, 'random_choice'],
  [/더 오래 걸|오래 걸/, 'long_time'],
  [/안녕|Hello|영어로 안녕|이름들을 알려|자기소개/, 'bow_greeting'],
  [/떡볶이|만드는 법/, 'cooking'],
  [/학교 가는 날/, 'book'],
  [/싫어|심심한 공부/, 'play'],
  [/이야기/, 'book'],
  [/틀렸을 때/, 'mistake_retry'],
  [/어른|부모님|선생님|알려요|알립니다|말해요|확인해요|확인하고.*지키고/, 'tell_adult'],
  [/숙제|공책|과제/, 'homework'],
  [/놀|놀이|게임/, 'play'],
  [/잠|자요|쉬어|휴식/, 'sleep'],
  [/화나|화난|화를|나쁜 말|기분 나쁜/, 'angry_face'],
  [/개인정보|주소|전화번호|비밀/, 'personal_info'],
  [/무조건.*믿|그대로 믿|바로 믿|그냥 다 믿|다 믿고.*말합니다/, 'blind_trust'],
  [/친구.*자랑|친구.*알려|친구한테/, 'tell_friend'],
  [/화면.*두드|두드리기|터치/, 'tap_screen'],
  [/밥|식사|먹었|먹고|아침밥|저녁/, 'meal'],
  [/그림|그려|사진|셀카|얼굴/, 'drawing'],
  [/챗봇|AI|인공지능/, 'chatbot'],
  [/음악|노래/, 'music'],
  [/비 오는|비\\b|우산/, 'umbrella'],
  [/구름/, 'cloud'],
  [/지도|길|정류장|버스/, 'map_app'],
  [/마트|장보기|물건|계산대|영수증|살 /, 'grocery_shopping'],
  [/날씨|맑|더운|추운/, 'weather'],
  [/청소|정리|쓸어요|쓸습니다|옷장|책꽂이/, 'tidy_room'],
  [/강아지|개\\b/, 'dog'],
  [/고양이/, 'cat'],
  [/토끼/, 'rabbit'],
  [/코끼리/, 'elephant'],
  [/공룡/, 'dinosaur'],
  [/거북이/, 'turtle'],
  [/치타/, 'cheetah'],
  [/독수리/, 'eagle'],
  [/동물/, 'cat'],
  [/책|도서관|글\\b/, 'book'],
  [/연필|글자 크게|써줘|쓰기|문장|요약|줄로|짧게|길게/, 'pencil'],
  [/지우개/, 'eraser'],
  [/사과|과일/, 'apple'],
  [/식빵|빵/, 'bread'],
  [/우유|물\\b/, 'milk'],
  [/치즈/, 'cheese'],
  [/햄/, 'ham'],
  [/초콜릿/, 'chocolate'],
  [/라면|면과 수프/, 'ramen'],
  [/냄비|끓/, 'pot'],
  [/토스터/, 'toaster'],
  [/칼|잘라요|반으로/, 'knife'],
  [/상추/, 'lettuce'],
  [/선글라스/, 'sunglasses'],
  [/부채/, 'hand_fan'],
  [/튜브/, 'tube'],
  [/열쇠|키\\b/, 'key'],
  [/전등|스위치/, 'light_switch'],
  [/스마트폰|핸드폰|화면|앱/, 'smartphone'],
  [/스피커|말로 대화/, 'ai_speaker'],
  [/요리사|요리|재료|만드는 순서/, 'cooking'],
  [/운전기사|운전/, 'job_driver'],
  [/사서/, 'job_librarian'],
  [/농부|채소/, 'job_farmer'],
  [/제빵사/, 'job_baker'],
  [/소방관/, 'job_firefighter'],
  [/수의사/, 'job_vet'],
  [/화가/, 'job_painter'],
  [/약|아파|참아요/, 'medicine'],
  [/인사|안녕하세요|감사합니다|죄송합니다|부탁/, 'bow_greeting'],
];

export function resolveActivityIcon(explicitIcon: string | undefined, label: string): string | undefined {
  if (explicitIcon) return explicitIcon;
  const normalized = label.replace(/[“”"]/g, '').trim();
  const rule = LABEL_ICON_RULES.find(([pattern]) => pattern.test(normalized));
  return rule?.[1];
}
