const LABEL_ICON_RULES: Array<[RegExp, string]> = [
  [/요리사|맛있는 음식/, 'job_chef'],
  [/운전기사|운전|버스나 트럭/, 'job_driver'],
  [/사서|도서관/, 'job_librarian'],
  [/농부|채소와 과일|길러요/, 'job_farmer'],
  [/제빵사/, 'job_baker'],
  [/소방관/, 'job_firefighter'],
  [/수의사/, 'job_vet'],
  [/화가/, 'job_painter'],
  [/버스|정류장|카드를 찍고|손잡이/, 'bus'],
  [/알람|시계|시간/, 'alarm_clock'],
  [/창문|창틀|커튼/, 'window'],
  [/어른|부모님|선생님|알려요|말해요|확인해요/, 'tell_adult'],
  [/숙제|공책|과제/, 'homework'],
  [/놀|놀이|게임/, 'play'],
  [/잠|자요|쉬어|휴식/, 'sleep'],
  [/화나|화난|화를|나쁜 말|기분 나쁜/, 'angry_face'],
  [/개인정보|주소|전화번호|비밀/, 'personal_info'],
  [/밥|식사|먹었|먹고|아침밥|저녁/, 'meal'],
  [/그림|그려|사진|셀카|얼굴/, 'drawing'],
  [/챗봇|AI|인공지능/, 'chatbot'],
  [/음악|노래/, 'music'],
  [/비 오는|비\\b|우산/, 'umbrella'],
  [/구름/, 'cloud'],
  [/지도|길|정류장|버스/, 'map_app'],
  [/마트|장보기|물건|계산대|영수증|살 /, 'grocery_shopping'],
  [/날씨|맑|더운|추운/, 'weather'],
  [/청소|정리|쓸어요|옷장|책꽂이/, 'tidy_room'],
  [/강아지|개\\b/, 'dog'],
  [/고양이/, 'cat'],
  [/토끼/, 'rabbit'],
  [/코끼리/, 'elephant'],
  [/공룡/, 'dinosaur'],
  [/거북이/, 'turtle'],
  [/치타/, 'cheetah'],
  [/독수리/, 'eagle'],
  [/동물/, 'cat'],
  [/책|도서관|글\\b/, 'book'],
  [/연필|써줘|쓰기|문장|요약|줄로|짧게|길게/, 'pencil'],
  [/지우개/, 'eraser'],
  [/사과|과일/, 'apple'],
  [/식빵|빵/, 'bread'],
  [/우유|물\\b/, 'milk'],
  [/치즈/, 'cheese'],
  [/햄/, 'ham'],
  [/초콜릿/, 'chocolate'],
  [/라면|면과 수프/, 'ramen'],
  [/냄비|끓/, 'pot'],
  [/토스터/, 'toaster'],
  [/칼|잘라요|반으로/, 'knife'],
  [/상추/, 'lettuce'],
  [/선글라스/, 'sunglasses'],
  [/부채/, 'hand_fan'],
  [/튜브/, 'tube'],
  [/열쇠|키\\b/, 'key'],
  [/전등|스위치/, 'light_switch'],
  [/스마트폰|핸드폰|화면|앱/, 'smartphone'],
  [/스피커|말로 대화/, 'ai_speaker'],
  [/요리사|요리|재료|만드는 순서/, 'cooking'],
  [/운전기사|운전/, 'job_driver'],
  [/사서/, 'job_librarian'],
  [/농부|채소/, 'job_farmer'],
  [/제빵사/, 'job_baker'],
  [/소방관/, 'job_firefighter'],
  [/수의사/, 'job_vet'],
  [/화가/, 'job_painter'],
  [/약|아파|참아요/, 'medicine'],
  [/인사|안녕하세요|감사합니다|죄송합니다|부탁/, 'bow_greeting'],
];

export function resolveActivityIcon(explicitIcon: string | undefined, label: string): string | undefined {
  if (explicitIcon) return explicitIcon;
  const normalized = label.replace(/[“”"]/g, '').trim();
  const rule = LABEL_ICON_RULES.find(([pattern]) => pattern.test(normalized));
  return rule?.[1];
}
